# action.yml
name: 'OpenFaaS deploy action helper'

description: 'Determines which functions needs to be acted upon'

inputs:
  caller:
    description: 'Tells which action will consume the output - deploy or build_push'
    default: 'build_push'
  force:
    description: 'Add passed function to output even if nothing is changed in the source code'
    default: 'none'

outputs:
  function-details:
    description: 'List of functions for strategy matrix'

runs:
  using: 'node12'
  main: 'helper.js'
