# action.yml
name: 'OpenFaaS deploy action helper'

description: 'Determines which functions needs to be acted upon'

inputs:
  stack-file:
    description: 'Path of stack.yml file'
    default: 'stack.yml'
  force:
    description: 'Add passed function to output even if nothing is changed in the source code'
  used-by:
    description: 'Tells which action will use the output - deploy or build_push'

outputs:
  function-list:
    description: 'List of functions for strategy matrix'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.stack-file }}
    - ${{ inputs.force }}
    - ${{ inputs.used-by }}
