# build.yml
name: 'Function build and push'
description: 'Build and Push FaaS functions'
outputs:
  status:
    description: 'Whether the process succeeded or failed'
runs:
  using: 'docker'
  image: 'Dockerfile'