# action.yml
name: 'OpenFaaS build and push action'

description: 'Builds and pushes OpenFaaS function'

inputs:
  stack-file:
    description: 'stack.yml path'
    default: 'stack.yml'
  docker-username:
    description: 'Username for GCP'
  docker-password:
    description: 'Password for GCP'
  tag:
    description: 'Image tag to be pushed'
    default: 'latest'
  custom-template-url:
    description: 'RH custom template url'
  image-registry:
    description: 'GCR [hostname]/[project-id]'
    default: 'gcr.io/platform-235214/'
  function-name:
    description: 'Function name'
    default: '.'
  group-path:
    description: 'Function group'
    default: '.'
  enable-image-push:
    description: 'Flag for pushing image to GCR'
    default: true
  faas-cli-version:
    description: 'faas-cli version to install'
    default: '0.14.1'

runs:
  using: 'node16'
  main: 'buildAndPush.js'
